id: os_ssh_server_alive_count_max_configure
title: "Set SSH Active Server Alive Maximum to Zero"
discussion: |
  SSH _MUST_ be configured with an Active Server Alive Maximum Count set to zero. Terminating an idle session within a short time period reduces the window of opportunity for unauthorized personnel to take control of a management session enabled on the console or console port that has been left unattended. In addition, quickly terminating an idle session or an incomplete login attempt will also free up resources committed by the managed network element.

  NOTE: /etc/ssh/ssh_config will be automatically modified to its original state following any update or major upgrade to the operating system.
check: |
  /usr/bin/grep -c "^ServerAliveCountMax 0" /etc/ssh/ssh_config
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/grep -q '^ServerAliveCountMax' /etc/ssh/ssh_config && /usr/bin/sed -i.bak  's/.*ServerAliveCountMax.*/ServerAliveCountMax 0/' /etc/ssh/ssh_config || /bin/echo 'ServerAliveCountMax 0' >> /etc/ssh/ssh_config
  ----
references:
  cce:
    - CCE-91005-9
  cci: 
    - N/A
  800-53r5:
    - SC-10
  800-53r4: 
    - SC-10
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.13.9
macOS:
  - "12.0"
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cnssi-1253
mobileconfig: false
mobileconfig_info: